// Code generated by hertz generator.

package stash

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/yi-nology/git-manage-service/biz/dal/db"
	stash "github.com/yi-nology/git-manage-service/biz/model/biz/stash"
	"github.com/yi-nology/git-manage-service/biz/service/audit"
	"github.com/yi-nology/git-manage-service/biz/service/git"
	"github.com/yi-nology/git-manage-service/pkg/response"
)

// ListStash .
// @router /api/v1/stash/list [GET]
func ListStash(ctx context.Context, c *app.RequestContext) {
	var req stash.ListStashRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(req.RepoKey)
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	gitSvc := git.NewGitService()
	stashes, err := gitSvc.StashList(repo.Path)
	if err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	// 转换为proto格式
	var entries []*stash.StashEntry
	for _, s := range stashes {
		entries = append(entries, &stash.StashEntry{
			Index:   int32(s.Index),
			Ref:     s.Ref,
			Message: s.Message,
			Branch:  s.Branch,
			Date:    s.Date,
		})
	}

	response.Success(c, map[string]interface{}{
		"stashes": entries,
	})
}

// SaveStash .
// @router /api/v1/stash/save [POST]
func SaveStash(ctx context.Context, c *app.RequestContext) {
	var req stash.SaveStashRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(req.RepoKey)
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	gitSvc := git.NewGitService()
	if err := gitSvc.StashSave(repo.Path, req.Message, req.IncludeUntracked); err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	audit.AuditSvc.Log(c, "STASH_SAVE", "repo:"+repo.Key, map[string]string{
		"message": req.Message,
	})
	response.Success(c, map[string]string{"message": "stash saved"})
}

// ApplyStash .
// @router /api/v1/stash/apply [POST]
func ApplyStash(ctx context.Context, c *app.RequestContext) {
	var req stash.ApplyStashRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(req.RepoKey)
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	gitSvc := git.NewGitService()
	if err := gitSvc.StashApply(repo.Path, int(req.Index)); err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	audit.AuditSvc.Log(c, "STASH_APPLY", "repo:"+repo.Key, map[string]interface{}{
		"index": req.Index,
	})
	response.Success(c, map[string]string{"message": "stash applied"})
}

// PopStash .
// @router /api/v1/stash/pop [POST]
func PopStash(ctx context.Context, c *app.RequestContext) {
	var req stash.PopStashRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(req.RepoKey)
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	gitSvc := git.NewGitService()
	if err := gitSvc.StashPop(repo.Path, int(req.Index)); err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	audit.AuditSvc.Log(c, "STASH_POP", "repo:"+repo.Key, map[string]interface{}{
		"index": req.Index,
	})
	response.Success(c, map[string]string{"message": "stash popped"})
}

// DropStash .
// @router /api/v1/stash/drop [POST]
func DropStash(ctx context.Context, c *app.RequestContext) {
	var req stash.DropStashRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(req.RepoKey)
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	gitSvc := git.NewGitService()
	if err := gitSvc.StashDrop(repo.Path, int(req.Index)); err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	audit.AuditSvc.Log(c, "STASH_DROP", "repo:"+repo.Key, map[string]interface{}{
		"index": req.Index,
	})
	response.Success(c, map[string]string{"message": "stash dropped"})
}

// ClearStash .
// @router /api/v1/stash/clear [POST]
func ClearStash(ctx context.Context, c *app.RequestContext) {
	var req stash.ClearStashRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(req.RepoKey)
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	gitSvc := git.NewGitService()
	if err := gitSvc.StashClear(repo.Path); err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	audit.AuditSvc.Log(c, "STASH_CLEAR", "repo:"+repo.Key, nil)
	response.Success(c, map[string]string{"message": "all stashes cleared"})
}
