// Code generated by hertz generator.

package spec

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _specMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _contentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getspeccontentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getspeccontentbypathMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _savespeccontentbypathMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createspecfileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletespecfileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _lintspecMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listspecfilesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _rulesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getlintrulesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatelintruleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createlintruleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _savespeccontentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getspectreeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _validatespecMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commitMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commitspecMw() []app.HandlerFunc {
	// your code...
	return nil
}
