// Code generated by hertz generator.

package patch

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _patchMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _applypatchMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _checkpatchMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpatchcontentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletepatchMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _downloadpatchMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _generatepatchMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listpatchesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _savepatchMw() []app.HandlerFunc {
	// your code...
	return nil
}
