// Code generated by hertz generator.

package file

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _fileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getblobMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getfilehistoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettreeMw() []app.HandlerFunc {
	// your code...
	return nil
}
