// Code generated by hertz generator.

package webhook

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _webhooksMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _triggersyncMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _triggerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _triggersyncbytokenMw() []app.HandlerFunc {
	// your code...
	return nil
}
