// Code generated by hertz generator.

package sshkey

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _systemMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dbsshkeysMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listdbsshkeysMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createdbsshkeyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdbsshkeyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatedbsshkeyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletedbsshkeyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _testdbsshkeyMw() []app.HandlerFunc {
	// your code...
	return nil
}
