// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBackendURL():Promise<string>;

export function GetBuildTime():Promise<string>;

export function GetGitCommit():Promise<string>;

export function GetVersion():Promise<string>;
