// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBackendURL() {
  return window['go']['desktop']['App']['GetBackendURL']();
}

export function GetBuildTime() {
  return window['go']['desktop']['App']['GetBuildTime']();
}

export function GetGitCommit() {
  return window['go']['desktop']['App']['GetGitCommit']();
}

export function GetVersion() {
  return window['go']['desktop']['App']['GetVersion']();
}
