// Code generated by hertz generator.

package notification

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/yi-nology/git-manage-service/biz/dal/db"
	notification "github.com/yi-nology/git-manage-service/biz/model/biz/notification"
	"github.com/yi-nology/git-manage-service/biz/model/po"
	"github.com/yi-nology/git-manage-service/biz/service/audit"
	notificationSvc "github.com/yi-nology/git-manage-service/biz/service/notification"
	"github.com/yi-nology/git-manage-service/pkg/response"
	"gorm.io/gorm"
)

// eventTemplateDTO 事件模板的 JSON 传输结构
type eventTemplateDTO struct {
	EventType       string `json:"event_type"`
	TitleTemplate   string `json:"title_template"`
	ContentTemplate string `json:"content_template"`
}

// channelToProto 将 PO 转换为 proto 格式
func channelToProto(ch *po.NotificationChannel) *notification.NotificationChannel {
	proto := &notification.NotificationChannel{
		Id:              int64(ch.ID),
		Name:            ch.Name,
		Type:            ch.Type,
		Config:          ch.Config,
		Enabled:         ch.Enabled,
		NotifyOnSuccess: ch.NotifyOnSuccess,
		NotifyOnFailure: ch.NotifyOnFailure,
		TriggerEvents:   ch.TriggerEvents,
		TitleTemplate:   ch.TitleTemplate,
		ContentTemplate: ch.ContentTemplate,
		CreatedAt:       ch.CreatedAt.Format("2006-01-02 15:04:05"),
		UpdatedAt:       ch.UpdatedAt.Format("2006-01-02 15:04:05"),
	}

	// 查询该渠道的事件模板并序列化为 JSON
	etDAO := db.NewNotificationEventTemplateDAO()
	templates, err := etDAO.FindByChannelID(ch.ID)
	if err == nil && len(templates) > 0 {
		dtos := make([]eventTemplateDTO, 0, len(templates))
		for _, t := range templates {
			dtos = append(dtos, eventTemplateDTO{
				EventType:       t.EventType,
				TitleTemplate:   t.TitleTemplate,
				ContentTemplate: t.ContentTemplate,
			})
		}
		if data, err := json.Marshal(dtos); err == nil {
			proto.EventTemplatesJson = string(data)
		}
	}

	return proto
}

// ListChannels .
// @router /api/v1/notification/channels [GET]
func ListChannels(ctx context.Context, c *app.RequestContext) {
	var req notification.ListChannelsRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	dao := db.NewNotificationChannelDAO()
	var channels []po.NotificationChannel
	var err error

	if req.Type != "" {
		channels, err = dao.FindByType(req.Type)
	} else {
		channels, err = dao.FindAll()
	}

	if err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	var items []*notification.NotificationChannel
	for _, ch := range channels {
		items = append(items, channelToProto(&ch))
	}

	response.Success(c, map[string]interface{}{
		"channels": items,
	})
}

// GetChannel .
// @router /api/v1/notification/channel [GET]
func GetChannel(ctx context.Context, c *app.RequestContext) {
	var req notification.GetChannelRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	dao := db.NewNotificationChannelDAO()
	channel, err := dao.FindByID(uint(req.Id))
	if err != nil {
		response.NotFound(c, "channel not found")
		return
	}

	response.Success(c, map[string]interface{}{
		"channel": channelToProto(channel),
	})
}

// CreateChannel .
// @router /api/v1/notification/channel/create [POST]
func CreateChannel(ctx context.Context, c *app.RequestContext) {
	var req notification.CreateChannelRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	// 验证渠道级模板语法
	if err := notificationSvc.ValidateTemplate(req.TitleTemplate); err != nil {
		response.BadRequest(c, "标题模板语法错误: "+err.Error())
		return
	}
	if err := notificationSvc.ValidateTemplate(req.ContentTemplate); err != nil {
		response.BadRequest(c, "内容模板语法错误: "+err.Error())
		return
	}

	// 解析并验证事件级模板
	var eventDTOs []eventTemplateDTO
	if req.EventTemplatesJson != "" {
		if err := json.Unmarshal([]byte(req.EventTemplatesJson), &eventDTOs); err != nil {
			response.BadRequest(c, "事件模板 JSON 格式错误: "+err.Error())
			return
		}
		for _, dto := range eventDTOs {
			if err := notificationSvc.ValidateTemplate(dto.TitleTemplate); err != nil {
				response.BadRequest(c, fmt.Sprintf("事件 %s 标题模板语法错误: %s", dto.EventType, err.Error()))
				return
			}
			if err := notificationSvc.ValidateTemplate(dto.ContentTemplate); err != nil {
				response.BadRequest(c, fmt.Sprintf("事件 %s 内容模板语法错误: %s", dto.EventType, err.Error()))
				return
			}
		}
	}

	channel := &po.NotificationChannel{
		Name:            req.Name,
		Type:            req.Type,
		Config:          req.Config,
		Enabled:         req.Enabled,
		NotifyOnSuccess: req.NotifyOnSuccess,
		NotifyOnFailure: req.NotifyOnFailure,
		TriggerEvents:   req.TriggerEvents,
		TitleTemplate:   req.TitleTemplate,
		ContentTemplate: req.ContentTemplate,
	}

	// 使用事务创建渠道和事件模板
	err := db.DB.Transaction(func(tx *gorm.DB) error {
		if err := tx.Create(channel).Error; err != nil {
			return err
		}
		if len(eventDTOs) > 0 {
			templates := make([]po.NotificationEventTemplate, 0, len(eventDTOs))
			for _, dto := range eventDTOs {
				templates = append(templates, po.NotificationEventTemplate{
					ChannelID:       channel.ID,
					EventType:       dto.EventType,
					TitleTemplate:   dto.TitleTemplate,
					ContentTemplate: dto.ContentTemplate,
				})
			}
			if err := tx.Create(&templates).Error; err != nil {
				return err
			}
		}
		return nil
	})
	if err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	audit.AuditSvc.Log(c, "NOTIFICATION_CHANNEL_CREATE", fmt.Sprintf("channel:%d", channel.ID), map[string]string{
		"name": req.Name,
		"type": req.Type,
	})

	response.Success(c, map[string]interface{}{
		"channel": channelToProto(channel),
	})
}

// UpdateChannel .
// @router /api/v1/notification/channel/update [POST]
func UpdateChannel(ctx context.Context, c *app.RequestContext) {
	var req notification.UpdateChannelRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	// 验证渠道级模板语法
	if err := notificationSvc.ValidateTemplate(req.TitleTemplate); err != nil {
		response.BadRequest(c, "标题模板语法错误: "+err.Error())
		return
	}
	if err := notificationSvc.ValidateTemplate(req.ContentTemplate); err != nil {
		response.BadRequest(c, "内容模板语法错误: "+err.Error())
		return
	}

	// 解析并验证事件级模板
	var eventDTOs []eventTemplateDTO
	if req.EventTemplatesJson != "" {
		if err := json.Unmarshal([]byte(req.EventTemplatesJson), &eventDTOs); err != nil {
			response.BadRequest(c, "事件模板 JSON 格式错误: "+err.Error())
			return
		}
		for _, dto := range eventDTOs {
			if err := notificationSvc.ValidateTemplate(dto.TitleTemplate); err != nil {
				response.BadRequest(c, fmt.Sprintf("事件 %s 标题模板语法错误: %s", dto.EventType, err.Error()))
				return
			}
			if err := notificationSvc.ValidateTemplate(dto.ContentTemplate); err != nil {
				response.BadRequest(c, fmt.Sprintf("事件 %s 内容模板语法错误: %s", dto.EventType, err.Error()))
				return
			}
		}
	}

	dao := db.NewNotificationChannelDAO()
	channel, err := dao.FindByID(uint(req.Id))
	if err != nil {
		response.NotFound(c, "channel not found")
		return
	}

	channel.Name = req.Name
	channel.Config = req.Config
	channel.Enabled = req.Enabled
	channel.NotifyOnSuccess = req.NotifyOnSuccess
	channel.NotifyOnFailure = req.NotifyOnFailure
	channel.TriggerEvents = req.TriggerEvents
	channel.TitleTemplate = req.TitleTemplate
	channel.ContentTemplate = req.ContentTemplate

	// 使用事务更新渠道和事件模板
	etDAO := db.NewNotificationEventTemplateDAO()
	err = db.DB.Transaction(func(tx *gorm.DB) error {
		if err := tx.Save(channel).Error; err != nil {
			return err
		}
		// 先删后插，替换该渠道的所有事件模板
		templates := make([]po.NotificationEventTemplate, 0, len(eventDTOs))
		for _, dto := range eventDTOs {
			templates = append(templates, po.NotificationEventTemplate{
				ChannelID:       channel.ID,
				EventType:       dto.EventType,
				TitleTemplate:   dto.TitleTemplate,
				ContentTemplate: dto.ContentTemplate,
			})
		}
		return etDAO.ReplaceByChannelID(tx, channel.ID, templates)
	})
	if err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	audit.AuditSvc.Log(c, "NOTIFICATION_CHANNEL_UPDATE", fmt.Sprintf("channel:%d", channel.ID), map[string]string{
		"name": req.Name,
	})

	response.Success(c, map[string]interface{}{
		"channel": channelToProto(channel),
	})
}

// DeleteChannel .
// @router /api/v1/notification/channel/delete [POST]
func DeleteChannel(ctx context.Context, c *app.RequestContext) {
	var req notification.DeleteChannelRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	dao := db.NewNotificationChannelDAO()
	channel, err := dao.FindByID(uint(req.Id))
	if err != nil {
		response.NotFound(c, "channel not found")
		return
	}

	// 使用事务级联删除事件模板和渠道
	etDAO := db.NewNotificationEventTemplateDAO()
	err = db.DB.Transaction(func(tx *gorm.DB) error {
		if err := etDAO.DeleteByChannelID(tx, channel.ID); err != nil {
			return err
		}
		return tx.Delete(channel).Error
	})
	if err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	audit.AuditSvc.Log(c, "NOTIFICATION_CHANNEL_DELETE", fmt.Sprintf("channel:%d", req.Id), nil)

	response.Success(c, map[string]string{"message": "channel deleted"})
}

// TestChannel .
// @router /api/v1/notification/channel/test [POST]
func TestChannel(ctx context.Context, c *app.RequestContext) {
	var req notification.TestChannelRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	message := req.Message
	if message == "" {
		message = "This is a test notification from Git Manage Service."
	}

	err := notificationSvc.NotifySvc.Test(uint(req.Id), message)
	if err != nil {
		response.Success(c, map[string]interface{}{
			"success": false,
			"error":   err.Error(),
		})
		return
	}

	response.Success(c, map[string]interface{}{
		"success": true,
	})
}
