// Code generated by hertz generator.

package notification

import (
	"context"
	"fmt"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/yi-nology/git-manage-service/biz/dal/db"
	notification "github.com/yi-nology/git-manage-service/biz/model/biz/notification"
	"github.com/yi-nology/git-manage-service/biz/model/po"
	"github.com/yi-nology/git-manage-service/biz/service/audit"
	notificationSvc "github.com/yi-nology/git-manage-service/biz/service/notification"
	"github.com/yi-nology/git-manage-service/pkg/response"
)

// channelToProto 将 PO 转换为 proto 格式
func channelToProto(ch *po.NotificationChannel) *notification.NotificationChannel {
	return &notification.NotificationChannel{
		Id:              int64(ch.ID),
		Name:            ch.Name,
		Type:            ch.Type,
		Config:          ch.Config,
		Enabled:         ch.Enabled,
		NotifyOnSuccess: ch.NotifyOnSuccess,
		NotifyOnFailure: ch.NotifyOnFailure,
		TriggerEvents:   ch.TriggerEvents,
		TitleTemplate:   ch.TitleTemplate,
		ContentTemplate: ch.ContentTemplate,
		CreatedAt:       ch.CreatedAt.Format("2006-01-02 15:04:05"),
		UpdatedAt:       ch.UpdatedAt.Format("2006-01-02 15:04:05"),
	}
}

// ListChannels .
// @router /api/v1/notification/channels [GET]
func ListChannels(ctx context.Context, c *app.RequestContext) {
	var req notification.ListChannelsRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	dao := db.NewNotificationChannelDAO()
	var channels []po.NotificationChannel
	var err error

	if req.Type != "" {
		channels, err = dao.FindByType(req.Type)
	} else {
		channels, err = dao.FindAll()
	}

	if err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	var items []*notification.NotificationChannel
	for _, ch := range channels {
		items = append(items, channelToProto(&ch))
	}

	response.Success(c, map[string]interface{}{
		"channels": items,
	})
}

// GetChannel .
// @router /api/v1/notification/channel [GET]
func GetChannel(ctx context.Context, c *app.RequestContext) {
	var req notification.GetChannelRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	dao := db.NewNotificationChannelDAO()
	channel, err := dao.FindByID(uint(req.Id))
	if err != nil {
		response.NotFound(c, "channel not found")
		return
	}

	response.Success(c, map[string]interface{}{
		"channel": channelToProto(channel),
	})
}

// CreateChannel .
// @router /api/v1/notification/channel/create [POST]
func CreateChannel(ctx context.Context, c *app.RequestContext) {
	var req notification.CreateChannelRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	// 验证模板语法
	if err := notificationSvc.ValidateTemplate(req.TitleTemplate); err != nil {
		response.BadRequest(c, "标题模板语法错误: "+err.Error())
		return
	}
	if err := notificationSvc.ValidateTemplate(req.ContentTemplate); err != nil {
		response.BadRequest(c, "内容模板语法错误: "+err.Error())
		return
	}

	channel := &po.NotificationChannel{
		Name:            req.Name,
		Type:            req.Type,
		Config:          req.Config,
		Enabled:         req.Enabled,
		NotifyOnSuccess: req.NotifyOnSuccess,
		NotifyOnFailure: req.NotifyOnFailure,
		TriggerEvents:   req.TriggerEvents,
		TitleTemplate:   req.TitleTemplate,
		ContentTemplate: req.ContentTemplate,
	}

	dao := db.NewNotificationChannelDAO()
	if err := dao.Create(channel); err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	audit.AuditSvc.Log(c, "NOTIFICATION_CHANNEL_CREATE", fmt.Sprintf("channel:%d", channel.ID), map[string]string{
		"name": req.Name,
		"type": req.Type,
	})

	response.Success(c, map[string]interface{}{
		"channel": channelToProto(channel),
	})
}

// UpdateChannel .
// @router /api/v1/notification/channel/update [POST]
func UpdateChannel(ctx context.Context, c *app.RequestContext) {
	var req notification.UpdateChannelRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	// 验证模板语法
	if err := notificationSvc.ValidateTemplate(req.TitleTemplate); err != nil {
		response.BadRequest(c, "标题模板语法错误: "+err.Error())
		return
	}
	if err := notificationSvc.ValidateTemplate(req.ContentTemplate); err != nil {
		response.BadRequest(c, "内容模板语法错误: "+err.Error())
		return
	}

	dao := db.NewNotificationChannelDAO()
	channel, err := dao.FindByID(uint(req.Id))
	if err != nil {
		response.NotFound(c, "channel not found")
		return
	}

	channel.Name = req.Name
	channel.Config = req.Config
	channel.Enabled = req.Enabled
	channel.NotifyOnSuccess = req.NotifyOnSuccess
	channel.NotifyOnFailure = req.NotifyOnFailure
	channel.TriggerEvents = req.TriggerEvents
	channel.TitleTemplate = req.TitleTemplate
	channel.ContentTemplate = req.ContentTemplate

	if err := dao.Save(channel); err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	audit.AuditSvc.Log(c, "NOTIFICATION_CHANNEL_UPDATE", fmt.Sprintf("channel:%d", channel.ID), map[string]string{
		"name": req.Name,
	})

	response.Success(c, map[string]interface{}{
		"channel": channelToProto(channel),
	})
}

// DeleteChannel .
// @router /api/v1/notification/channel/delete [POST]
func DeleteChannel(ctx context.Context, c *app.RequestContext) {
	var req notification.DeleteChannelRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	dao := db.NewNotificationChannelDAO()
	channel, err := dao.FindByID(uint(req.Id))
	if err != nil {
		response.NotFound(c, "channel not found")
		return
	}

	if err := dao.Delete(channel); err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	audit.AuditSvc.Log(c, "NOTIFICATION_CHANNEL_DELETE", fmt.Sprintf("channel:%d", req.Id), nil)

	response.Success(c, map[string]string{"message": "channel deleted"})
}

// TestChannel .
// @router /api/v1/notification/channel/test [POST]
func TestChannel(ctx context.Context, c *app.RequestContext) {
	var req notification.TestChannelRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	message := req.Message
	if message == "" {
		message = "This is a test notification from Git Manage Service."
	}

	err := notificationSvc.NotifySvc.Test(uint(req.Id), message)
	if err != nil {
		response.Success(c, map[string]interface{}{
			"success": false,
			"error":   err.Error(),
		})
		return
	}

	response.Success(c, map[string]interface{}{
		"success": true,
	})
}
