// Code generated by Kitex v0.15.2. DO NOT EDIT.

package git

import (
	"context"

	"github.com/cloudwego/prutal"
)

type Repo struct {
	Id          int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Key         string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	RemoteUrl   string `protobuf:"bytes,5,opt,name=remote_url" json:"remote_url,omitempty"`
	Status      string `protobuf:"bytes,6,opt,name=status" json:"status,omitempty"`
}

func (x *Repo) Reset() { *x = Repo{} }

func (x *Repo) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Repo) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Repo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Repo) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Repo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Repo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Repo) GetRemoteUrl() string {
	if x != nil {
		return x.RemoteUrl
	}
	return ""
}

func (x *Repo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Branch struct {
	Name          string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	CommitHash    string `protobuf:"bytes,2,opt,name=commit_hash" json:"commit_hash,omitempty"`
	CommitMessage string `protobuf:"bytes,3,opt,name=commit_message" json:"commit_message,omitempty"`
	Author        string `protobuf:"bytes,4,opt,name=author" json:"author,omitempty"`
	Date          string `protobuf:"bytes,5,opt,name=date" json:"date,omitempty"`
	IsCurrent     bool   `protobuf:"varint,6,opt,name=is_current" json:"is_current,omitempty"`
}

func (x *Branch) Reset() { *x = Branch{} }

func (x *Branch) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Branch) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Branch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Branch) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *Branch) GetCommitMessage() string {
	if x != nil {
		return x.CommitMessage
	}
	return ""
}

func (x *Branch) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Branch) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Branch) GetIsCurrent() bool {
	if x != nil {
		return x.IsCurrent
	}
	return false
}

type ListReposRequest struct {
	Page     int32 `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
	PageSize int32 `protobuf:"varint,2,opt,name=page_size" json:"page_size,omitempty"`
}

func (x *ListReposRequest) Reset() { *x = ListReposRequest{} }

func (x *ListReposRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListReposRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListReposRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListReposRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListReposResponse struct {
	Repos []*Repo `protobuf:"bytes,1,rep,name=repos" json:"repos,omitempty"`
	Total int64   `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`
}

func (x *ListReposResponse) Reset() { *x = ListReposResponse{} }

func (x *ListReposResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListReposResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListReposResponse) GetRepos() []*Repo {
	if x != nil {
		return x.Repos
	}
	return nil
}

func (x *ListReposResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetRepoRequest struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (x *GetRepoRequest) Reset() { *x = GetRepoRequest{} }

func (x *GetRepoRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetRepoRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetRepoRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetRepoResponse struct {
	Repo *Repo `protobuf:"bytes,1,opt,name=repo" json:"repo,omitempty"`
}

func (x *GetRepoResponse) Reset() { *x = GetRepoResponse{} }

func (x *GetRepoResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetRepoResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetRepoResponse) GetRepo() *Repo {
	if x != nil {
		return x.Repo
	}
	return nil
}

type ListBranchesRequest struct {
	RepoKey string `protobuf:"bytes,1,opt,name=repo_key" json:"repo_key,omitempty"`
}

func (x *ListBranchesRequest) Reset() { *x = ListBranchesRequest{} }

func (x *ListBranchesRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListBranchesRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListBranchesRequest) GetRepoKey() string {
	if x != nil {
		return x.RepoKey
	}
	return ""
}

type ListBranchesResponse struct {
	Branches []*Branch `protobuf:"bytes,1,rep,name=branches" json:"branches,omitempty"`
}

func (x *ListBranchesResponse) Reset() { *x = ListBranchesResponse{} }

func (x *ListBranchesResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListBranchesResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListBranchesResponse) GetBranches() []*Branch {
	if x != nil {
		return x.Branches
	}
	return nil
}

type CreateBranchRequest struct {
	RepoKey    string `protobuf:"bytes,1,opt,name=repo_key" json:"repo_key,omitempty"`
	BranchName string `protobuf:"bytes,2,opt,name=branch_name" json:"branch_name,omitempty"`
	Ref        string `protobuf:"bytes,3,opt,name=ref" json:"ref,omitempty"` // Source ref (branch/commit)
}

func (x *CreateBranchRequest) Reset() { *x = CreateBranchRequest{} }

func (x *CreateBranchRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CreateBranchRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreateBranchRequest) GetRepoKey() string {
	if x != nil {
		return x.RepoKey
	}
	return ""
}

func (x *CreateBranchRequest) GetBranchName() string {
	if x != nil {
		return x.BranchName
	}
	return ""
}

func (x *CreateBranchRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

type CreateBranchResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (x *CreateBranchResponse) Reset() { *x = CreateBranchResponse{} }

func (x *CreateBranchResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CreateBranchResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreateBranchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateBranchResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteBranchRequest struct {
	RepoKey    string `protobuf:"bytes,1,opt,name=repo_key" json:"repo_key,omitempty"`
	BranchName string `protobuf:"bytes,2,opt,name=branch_name" json:"branch_name,omitempty"`
	Force      bool   `protobuf:"varint,3,opt,name=force" json:"force,omitempty"`
}

func (x *DeleteBranchRequest) Reset() { *x = DeleteBranchRequest{} }

func (x *DeleteBranchRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DeleteBranchRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeleteBranchRequest) GetRepoKey() string {
	if x != nil {
		return x.RepoKey
	}
	return ""
}

func (x *DeleteBranchRequest) GetBranchName() string {
	if x != nil {
		return x.BranchName
	}
	return ""
}

func (x *DeleteBranchRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type DeleteBranchResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (x *DeleteBranchResponse) Reset() { *x = DeleteBranchResponse{} }

func (x *DeleteBranchResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DeleteBranchResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeleteBranchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteBranchResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GitService interface {
	ListRepos(ctx context.Context, req *ListReposRequest) (res *ListReposResponse, err error)
	GetRepo(ctx context.Context, req *GetRepoRequest) (res *GetRepoResponse, err error)
	ListBranches(ctx context.Context, req *ListBranchesRequest) (res *ListBranchesResponse, err error)
	CreateBranch(ctx context.Context, req *CreateBranchRequest) (res *CreateBranchResponse, err error)
	DeleteBranch(ctx context.Context, req *DeleteBranchRequest) (res *DeleteBranchResponse, err error)
}
