// Code generated by hertz generator.

package submodule

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/yi-nology/git-manage-service/biz/dal/db"
	submodule "github.com/yi-nology/git-manage-service/biz/model/biz/submodule"
	"github.com/yi-nology/git-manage-service/biz/service/audit"
	"github.com/yi-nology/git-manage-service/biz/service/git"
	"github.com/yi-nology/git-manage-service/pkg/response"
)

// ListSubmodules .
// @router /api/v1/submodule/list [GET]
func ListSubmodules(ctx context.Context, c *app.RequestContext) {
	var req submodule.ListSubmodulesRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(req.RepoKey)
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	gitSvc := git.NewGitService()
	submodules, err := gitSvc.SubmoduleList(repo.Path)
	if err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	// 转换为proto格式
	var items []*submodule.SubmoduleInfo
	for _, sm := range submodules {
		items = append(items, &submodule.SubmoduleInfo{
			Name:   sm.Name,
			Path:   sm.Path,
			Url:    sm.URL,
			Branch: sm.Branch,
			Commit: sm.Commit,
			Status: sm.Status,
		})
	}

	response.Success(c, map[string]interface{}{
		"submodules": items,
	})
}

// GetStatus .
// @router /api/v1/submodule/status [GET]
func GetStatus(ctx context.Context, c *app.RequestContext) {
	var req submodule.GetSubmoduleStatusRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(req.RepoKey)
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	gitSvc := git.NewGitService()
	statusItems, err := gitSvc.SubmoduleStatus(repo.Path, req.Recursive)
	if err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	// 转换为proto格式
	var items []*submodule.SubmoduleStatusItem
	for _, item := range statusItems {
		items = append(items, &submodule.SubmoduleStatusItem{
			Path:        item.Path,
			Commit:      item.Commit,
			Status:      item.Status,
			Description: item.Description,
		})
	}

	response.Success(c, map[string]interface{}{
		"items": items,
	})
}

// AddSubmodule .
// @router /api/v1/submodule/add [POST]
func AddSubmodule(ctx context.Context, c *app.RequestContext) {
	var req submodule.AddSubmoduleRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(req.RepoKey)
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	gitSvc := git.NewGitService()
	if err := gitSvc.SubmoduleAdd(repo.Path, req.Url, req.Path, req.Branch); err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	audit.AuditSvc.Log(c, "SUBMODULE_ADD", "repo:"+repo.Key, map[string]string{
		"url":    req.Url,
		"path":   req.Path,
		"branch": req.Branch,
	})
	response.Success(c, map[string]string{"message": "submodule added"})
}

// InitSubmodule .
// @router /api/v1/submodule/init [POST]
func InitSubmodule(ctx context.Context, c *app.RequestContext) {
	var req submodule.InitSubmoduleRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(req.RepoKey)
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	gitSvc := git.NewGitService()
	if err := gitSvc.SubmoduleInit(repo.Path, req.Path); err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	audit.AuditSvc.Log(c, "SUBMODULE_INIT", "repo:"+repo.Key, map[string]string{
		"path": req.Path,
	})
	response.Success(c, map[string]string{"message": "submodule initialized"})
}

// UpdateSubmodule .
// @router /api/v1/submodule/update [POST]
func UpdateSubmodule(ctx context.Context, c *app.RequestContext) {
	var req submodule.UpdateSubmoduleRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(req.RepoKey)
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	gitSvc := git.NewGitService()
	if err := gitSvc.SubmoduleUpdate(repo.Path, req.Path, req.Init, req.Recursive, req.Remote); err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	audit.AuditSvc.Log(c, "SUBMODULE_UPDATE", "repo:"+repo.Key, map[string]interface{}{
		"path":      req.Path,
		"init":      req.Init,
		"recursive": req.Recursive,
		"remote":    req.Remote,
	})
	response.Success(c, map[string]string{"message": "submodule updated"})
}

// SyncSubmodule .
// @router /api/v1/submodule/sync [POST]
func SyncSubmodule(ctx context.Context, c *app.RequestContext) {
	var req submodule.SyncSubmoduleRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(req.RepoKey)
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	gitSvc := git.NewGitService()
	if err := gitSvc.SubmoduleSync(repo.Path, req.Path, req.Recursive); err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	audit.AuditSvc.Log(c, "SUBMODULE_SYNC", "repo:"+repo.Key, map[string]interface{}{
		"path":      req.Path,
		"recursive": req.Recursive,
	})
	response.Success(c, map[string]string{"message": "submodule synced"})
}

// RemoveSubmodule .
// @router /api/v1/submodule/remove [POST]
func RemoveSubmodule(ctx context.Context, c *app.RequestContext) {
	var req submodule.RemoveSubmoduleRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(req.RepoKey)
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	gitSvc := git.NewGitService()
	if err := gitSvc.SubmoduleRemove(repo.Path, req.Path, req.Force); err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	audit.AuditSvc.Log(c, "SUBMODULE_REMOVE", "repo:"+repo.Key, map[string]interface{}{
		"path":  req.Path,
		"force": req.Force,
	})
	response.Success(c, map[string]string{"message": "submodule removed"})
}
