// Code generated by hertz generator.

package notification

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _notificationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _channelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getchannelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createchannelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletechannelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _testchannelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatechannelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listchannelsMw() []app.HandlerFunc {
	// your code...
	return nil
}
