// Code generated by hertz generator.

package webhook

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/google/uuid"
	"github.com/yi-nology/git-manage-service/biz/dal/db"
	webhook "github.com/yi-nology/git-manage-service/biz/model/biz/webhook"
	"github.com/yi-nology/git-manage-service/biz/model/po"
	"github.com/yi-nology/git-manage-service/biz/service/audit"
	"github.com/yi-nology/git-manage-service/biz/service/sync"
	"github.com/yi-nology/git-manage-service/pkg/response"
)

// TriggerSync .
// @router /api/webhooks/task-sync [POST]
func TriggerSync(ctx context.Context, c *app.RequestContext) {
	var req webhook.TriggerSyncRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	// 支持task_key或task_id
	taskKey := req.TaskKey
	if taskKey == "" {
		taskKey = req.TaskId
	}
	if taskKey == "" {
		response.BadRequest(c, "task_key or task_id is required")
		return
	}

	// 查找任务
	dao := db.NewSyncTaskDAO()
	task, err := dao.FindByKey(taskKey)
	if err != nil {
		response.NotFound(c, "task not found")
		return
	}

	// 生成执行ID
	runID := uuid.New().String()

	// 异步执行同步任务
	go func() {
		syncSvc := sync.NewSyncService()
		syncSvc.ExecuteSyncWithTrigger(task, po.TriggerSourceWebhook)
	}()

	audit.AuditSvc.Log(c, "WEBHOOK_TRIGGER", "task:"+task.Key, map[string]string{
		"run_id": runID,
	})

	response.Success(c, map[string]interface{}{
		"run_id":   runID,
		"task_key": task.Key,
		"status":   "started",
		"message":  "sync task triggered",
	})
}

// TriggerSyncByToken .
// @router /api/webhooks/trigger/:token [POST]
func TriggerSyncByToken(ctx context.Context, c *app.RequestContext) {
	var req webhook.TriggerSyncByTokenRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	token := req.Token
	if token == "" {
		token = c.Param("token")
	}
	if token == "" {
		response.BadRequest(c, "token is required")
		return
	}

	// 通过token查找任务
	dao := db.NewSyncTaskDAO()
	task, err := dao.FindByWebhookToken(token)
	if err != nil {
		response.NotFound(c, "task not found for this token")
		return
	}

	// 生成执行ID
	runID := uuid.New().String()

	// 异步执行同步任务
	go func() {
		syncSvc := sync.NewSyncService()
		syncSvc.ExecuteSyncWithTrigger(task, po.TriggerSourceWebhook)
	}()

	audit.AuditSvc.Log(c, "WEBHOOK_TRIGGER_BY_TOKEN", "task:"+task.Key, map[string]string{
		"run_id": runID,
	})

	response.Success(c, map[string]interface{}{
		"run_id":   runID,
		"task_key": task.Key,
		"status":   "started",
		"message":  "sync task triggered by token",
	})
}
