// Code generated by hertz generator.

package submodule

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _submoduleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addsubmoduleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _initsubmoduleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listsubmodulesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _removesubmoduleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getstatusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _syncsubmoduleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatesubmoduleMw() []app.HandlerFunc {
	// your code...
	return nil
}
