// Code generated by hertz generator.

package branch

import (
	"context"
	"fmt"
	"strconv"
	"strings"
	"time"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/google/uuid"
	"github.com/yi-nology/git-manage-service/biz/dal/db"
	"github.com/yi-nology/git-manage-service/biz/model/branch"
	"github.com/yi-nology/git-manage-service/biz/model/domain"
	"github.com/yi-nology/git-manage-service/biz/service/audit"
	"github.com/yi-nology/git-manage-service/biz/service/auth"
	"github.com/yi-nology/git-manage-service/biz/service/git"
	"github.com/yi-nology/git-manage-service/pkg/response"
)

// CherryPick .
// @router /api/v1/branch/cherry-pick [POST]
func CherryPick(ctx context.Context, c *app.RequestContext) {
	var req branch.CherryPickRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(req.GetRepoKey())
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	gitSvc := git.NewGitService()
	newCommit, conflicts, err := gitSvc.CherryPick(repo.Path, req.GetCommitHash(), false)
	if err != nil {
		if len(conflicts) > 0 {
			// 返回冲突信息
			c.JSON(200, response.Response{
				Code: 409,
				Msg:  "Cherry-pick conflict",
				Data: map[string]interface{}{
					"conflicts": conflicts,
				},
			})
			return
		}
		response.InternalServerError(c, err.Error())
		return
	}

	audit.AuditSvc.Log(c, "CHERRY_PICK", "repo:"+repo.Key, map[string]string{
		"commit":     req.GetCommitHash(),
		"new_commit": newCommit,
	})
	response.Success(c, map[string]interface{}{
		"success":    true,
		"new_commit": newCommit,
	})
}

// Rebase .
// @router /api/v1/branch/rebase [POST]
func Rebase(ctx context.Context, c *app.RequestContext) {
	var req branch.RebaseRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(req.GetRepoKey())
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	gitSvc := git.NewGitService()
	success, conflicts, err := gitSvc.Rebase(repo.Path, req.GetUpstream(), "")
	if err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	if !success {
		c.JSON(200, response.Response{
			Code: 409,
			Msg:  "Rebase conflict",
			Data: map[string]interface{}{
				"success":     false,
				"in_progress": true,
				"conflicts":   conflicts,
			},
		})
		return
	}

	audit.AuditSvc.Log(c, "REBASE", "repo:"+repo.Key, map[string]string{
		"upstream": req.GetUpstream(),
	})
	response.Success(c, map[string]interface{}{
		"success":     true,
		"in_progress": false,
	})
}

// RebaseAbort .
// @router /api/v1/branch/rebase/abort [POST]
func RebaseAbort(ctx context.Context, c *app.RequestContext) {
	repoKey := c.Query("repo_key")
	if repoKey == "" {
		response.BadRequest(c, "repo_key is required")
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(repoKey)
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	gitSvc := git.NewGitService()
	if err := gitSvc.RebaseAbort(repo.Path); err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	audit.AuditSvc.Log(c, "REBASE_ABORT", "repo:"+repo.Key, nil)
	response.Success(c, map[string]string{"message": "rebase aborted"})
}

// RebaseContinue .
// @router /api/v1/branch/rebase/continue [POST]
func RebaseContinue(ctx context.Context, c *app.RequestContext) {
	repoKey := c.Query("repo_key")
	if repoKey == "" {
		response.BadRequest(c, "repo_key is required")
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(repoKey)
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	gitSvc := git.NewGitService()
	success, conflicts, err := gitSvc.RebaseContinue(repo.Path)
	if err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	if !success {
		c.JSON(200, response.Response{
			Code: 409,
			Msg:  "Rebase conflict",
			Data: map[string]interface{}{
				"success":     false,
				"in_progress": true,
				"conflicts":   conflicts,
			},
		})
		return
	}

	audit.AuditSvc.Log(c, "REBASE_CONTINUE", "repo:"+repo.Key, nil)
	response.Success(c, map[string]interface{}{
		"success":     true,
		"in_progress": false,
	})
}

// List .
// @router /api/v1/branch/list [GET]
func List(ctx context.Context, c *app.RequestContext) {
	var req branch.ListBranchRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	if req.GetRepoKey() == "" {
		response.BadRequest(c, "repo_key is required")
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(req.GetRepoKey())
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	gitSvc := git.NewGitService()
	branches, err := gitSvc.ListBranchesWithInfo(repo.Path)
	if err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	// Filter by type (local/remote)
	branchTypeFilter := c.Query("type")
	if branchTypeFilter != "" && (branchTypeFilter == "local" || branchTypeFilter == "remote") {
		var filtered []domain.BranchInfo
		for _, b := range branches {
			if b.Type == branchTypeFilter {
				filtered = append(filtered, b)
			}
		}
		branches = filtered
	}

	// Filter
	if req.GetKeyword() != "" {
		var filtered []domain.BranchInfo
		keyword := strings.ToLower(req.GetKeyword())
		for _, b := range branches {
			if strings.Contains(strings.ToLower(b.Name), keyword) ||
				strings.Contains(strings.ToLower(b.Author), keyword) {
				filtered = append(filtered, b)
			}
		}
		branches = filtered
	}

	// Pagination
	page := int(req.GetPage())
	if page < 1 {
		page = 1
	}
	pageSize := int(req.GetPageSize())
	if pageSize < 1 {
		pageSize = 100
	}

	start := (page - 1) * pageSize
	end := start + pageSize
	if start > len(branches) {
		start = len(branches)
	}
	if end > len(branches) {
		end = len(branches)
	}

	paged := branches[start:end]

	for i := range paged {
		b := &paged[i]
		if b.Upstream != "" {
			ahead, behind, _ := gitSvc.GetBranchSyncStatus(repo.Path, b.Name, b.Upstream)
			b.Ahead = ahead
			b.Behind = behind
		}
	}

	response.Success(c, map[string]interface{}{
		"total": len(branches),
		"list":  paged,
	})
}

// Create .
// @router /api/v1/branch/create [POST]
func Create(ctx context.Context, c *app.RequestContext) {
	var req branch.CreateBranchRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(req.GetRepoKey())
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	gitSvc := git.NewGitService()
	if err := gitSvc.CreateBranch(repo.Path, req.GetName(), req.GetBaseRef()); err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	audit.AuditSvc.Log(c, "CREATE_BRANCH", "repo:"+repo.Key, map[string]string{
		"branch": req.GetName(),
		"base":   req.GetBaseRef(),
	})
	response.Success(c, map[string]string{"message": "created"})
}

// Delete .
// @router /api/v1/branch/delete [POST]
func Delete(ctx context.Context, c *app.RequestContext) {
	var req branch.DeleteBranchRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(req.GetRepoKey())
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	gitSvc := git.NewGitService()
	if err := gitSvc.DeleteBranch(repo.Path, req.GetName(), req.GetForce()); err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	audit.AuditSvc.Log(c, "DELETE_BRANCH", "repo:"+repo.Key, map[string]string{
		"branch": req.GetName(),
		"force":  strconv.FormatBool(req.GetForce()),
	})
	response.Success(c, map[string]string{"message": "deleted"})
}

// Update .
// @router /api/v1/branch/update [POST]
func Update(ctx context.Context, c *app.RequestContext) {
	var req branch.UpdateBranchRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(req.GetRepoKey())
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	gitSvc := git.NewGitService()
	currentName := req.GetName()

	// Rename
	if req.GetNewName() != "" && req.GetNewName() != currentName {
		if err := gitSvc.RenameBranch(repo.Path, currentName, req.GetNewName()); err != nil {
			response.InternalServerError(c, err.Error())
			return
		}
		currentName = req.GetNewName()
	}

	// Description
	if req.GetDesc() != "" {
		if err := gitSvc.SetBranchDescription(repo.Path, currentName, req.GetDesc()); err != nil {
			// Log but don't fail
		}
	}

	audit.AuditSvc.Log(c, "UPDATE_BRANCH", "repo:"+repo.Key, map[string]string{
		"old_name": req.GetName(),
		"new_name": req.GetNewName(),
		"desc":     req.GetDesc(),
	})
	response.Success(c, map[string]string{"message": "updated"})
}

// Checkout .
// @router /api/v1/branch/checkout [POST]
func Checkout(ctx context.Context, c *app.RequestContext) {
	var req branch.CheckoutBranchRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(req.GetRepoKey())
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	gitSvc := git.NewGitService()
	if err := gitSvc.CheckoutBranch(repo.Path, req.GetName()); err != nil {
		response.BadRequest(c, "Checkout failed: "+err.Error())
		return
	}

	audit.AuditSvc.Log(c, "CHECKOUT_BRANCH", "repo:"+repo.Key, map[string]string{
		"branch": req.GetName(),
	})
	response.Success(c, map[string]string{"message": "checked out " + req.GetName()})
}

// Push .
// @router /api/v1/branch/push [POST]
func Push(ctx context.Context, c *app.RequestContext) {
	var req branch.PushBranchRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(req.GetRepoKey())
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	gitSvc := git.NewGitService()
	authSvc := auth.NewAuthService()

	var errors []string
	for _, remote := range req.GetRemotes() {
		// 获取该 remote 的认证配置
		authInfo := auth.GetAuthInfoForRemote(repo.RemoteAuths, remote, repo.AuthType, repo.AuthKey, repo.AuthSecret)

		// 如果配置了数据库 SSH 密钥，使用原生 git 命令
		if authInfo.Type == "ssh" && authInfo.Source == "database" && authInfo.SSHKeyID > 0 {
			privateKey, passphrase, err := authSvc.GetDBSSHKeyContent(authInfo.SSHKeyID)
			if err != nil {
				errors = append(errors, fmt.Sprintf("%s: failed to load SSH key: %v", remote, err))
				continue
			}
			if err := gitSvc.PushBranchWithDBKey(repo.Path, remote, req.GetName(), privateKey, passphrase); err != nil {
				errors = append(errors, fmt.Sprintf("%s: %v", remote, err))
			}
		} else {
			// 使用 go-git 默认方式
			if err := gitSvc.PushBranch(repo.Path, remote, req.GetName()); err != nil {
				errors = append(errors, fmt.Sprintf("%s: %v", remote, err))
			}
		}
	}

	if len(errors) > 0 {
		response.InternalServerError(c, strings.Join(errors, "; "))
		return
	}

	audit.AuditSvc.Log(c, "PUSH_BRANCH", "repo:"+repo.Key, map[string]interface{}{
		"branch":  req.GetName(),
		"remotes": req.GetRemotes(),
	})
	response.Success(c, map[string]string{"message": "pushed"})
}

// Pull .
// @router /api/v1/branch/pull [POST]
func Pull(ctx context.Context, c *app.RequestContext) {
	var req branch.PullBranchRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(req.GetRepoKey())
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	gitSvc := git.NewGitService()
	authSvc := auth.NewAuthService()
	branches, _ := gitSvc.ListBranchesWithInfo(repo.Path)

	var isCurrent bool
	var upstreamRemote string
	var remoteBranch string

	for _, b := range branches {
		if b.Name == req.GetName() {
			isCurrent = b.IsCurrent
			if b.Upstream != "" {
				parts := strings.Split(b.Upstream, "/")
				if len(parts) > 0 {
					upstreamRemote = parts[0]
					if len(parts) > 1 {
						remoteBranch = strings.Join(parts[1:], "/")
					}
				}
			}
			break
		}
	}

	if upstreamRemote == "" {
		response.BadRequest(c, "No upstream configured for this branch")
		return
	}

	if remoteBranch == "" {
		remoteBranch = req.GetName()
	}

	// 获取该 remote 的认证配置
	authInfo := auth.GetAuthInfoForRemote(repo.RemoteAuths, upstreamRemote, repo.AuthType, repo.AuthKey, repo.AuthSecret)

	// 检查是否使用数据库 SSH 密钥
	useDBKey := authInfo.Type == "ssh" && authInfo.Source == "database" && authInfo.SSHKeyID > 0
	var privateKey, passphrase string
	if useDBKey {
		privateKey, passphrase, err = authSvc.GetDBSSHKeyContent(authInfo.SSHKeyID)
		if err != nil {
			response.InternalServerError(c, fmt.Sprintf("failed to load SSH key: %v", err))
			return
		}
	}

	if !isCurrent {
		var updateErr error
		if useDBKey {
			updateErr = gitSvc.FetchBranchWithDBKey(repo.Path, upstreamRemote, remoteBranch, privateKey, passphrase)
		} else {
			updateErr = gitSvc.UpdateBranchFastForward(repo.Path, upstreamRemote, req.GetName(), remoteBranch)
		}
		if updateErr != nil {
			response.InternalServerError(c, fmt.Sprintf("Update failed (must be fast-forward): %v", updateErr))
			return
		}

		audit.AuditSvc.Log(c, "UPDATE_BRANCH", "repo:"+repo.Key, map[string]string{
			"branch": req.GetName(),
			"remote": upstreamRemote,
			"type":   "fast-forward",
		})
		response.Success(c, map[string]string{"message": "updated (fast-forward)"})
		return
	}

	var pullErr error
	if useDBKey {
		pullErr = gitSvc.PullBranchWithDBKey(repo.Path, upstreamRemote, req.GetName(), privateKey, passphrase)
	} else {
		pullErr = gitSvc.PullBranch(repo.Path, upstreamRemote, req.GetName())
	}
	if pullErr != nil {
		response.InternalServerError(c, pullErr.Error())
		return
	}

	audit.AuditSvc.Log(c, "PULL_BRANCH", "repo:"+repo.Key, map[string]string{
		"branch": req.GetName(),
		"remote": upstreamRemote,
	})
	response.Success(c, map[string]string{"message": "synced"})
}

// Compare .
// @router /api/v1/branch/compare [GET]
func Compare(ctx context.Context, c *app.RequestContext) {
	var req branch.CompareBranchRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(req.GetRepoKey())
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	gitSvc := git.NewGitService()

	stat, err := gitSvc.GetDiffStat(repo.Path, req.GetBase(), req.GetTarget())
	if err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	files, err := gitSvc.GetDiffFiles(repo.Path, req.GetBase(), req.GetTarget())
	if err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	response.Success(c, map[string]interface{}{
		"stat":  stat,
		"files": files,
	})
}

// Merge .
// @router /api/v1/branch/merge [POST]
func Merge(ctx context.Context, c *app.RequestContext) {
	var req branch.MergeBranchRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(req.GetRepoKey())
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	gitSvc := git.NewGitService()

	check, err := gitSvc.MergeDryRun(repo.Path, req.GetSource(), req.GetTarget())
	if err != nil {
		response.InternalServerError(c, "Pre-merge check failed: "+err.Error())
		return
	}
	if !check.Success {
		mergeID := uuid.New().String()
		reportURL := fmt.Sprintf("/merge_report.html?repo_key=%s&source=%s&target=%s&merge_id=%s", repo.Key, req.GetSource(), req.GetTarget(), mergeID)

		audit.AuditSvc.Log(c, "MERGE_CONFLICT", "repo:"+repo.Key, map[string]interface{}{
			"source":    req.GetSource(),
			"target":    req.GetTarget(),
			"conflicts": check.Conflicts,
			"merge_id":  mergeID,
		})

		c.JSON(200, response.Response{
			Code: 409,
			Msg:  "Merge conflict detected",
			Data: map[string]interface{}{
				"conflicts":  check.Conflicts,
				"report_url": reportURL,
				"merge_id":   mergeID,
			},
		})
		return
	}

	if err := gitSvc.Merge(repo.Path, req.GetSource(), req.GetTarget(), req.GetMessage(), req.GetNoFf(), req.GetSquash()); err != nil {
		response.InternalServerError(c, "Merge execution failed: "+err.Error())
		return
	}

	audit.AuditSvc.Log(c, "MERGE_SUCCESS", "repo:"+repo.Key, map[string]string{
		"source": req.GetSource(),
		"target": req.GetTarget(),
	})

	response.Success(c, map[string]string{"status": "merged"})
}

// MergeCheck .
// @router /api/v1/branch/merge/check [GET]
func MergeCheck(ctx context.Context, c *app.RequestContext) {
	var req branch.MergeCheckRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(req.GetRepoKey())
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	gitSvc := git.NewGitService()
	result, err := gitSvc.MergeDryRun(repo.Path, req.GetBase(), req.GetTarget())
	if err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	response.Success(c, result)
}

// GetDiff .
// @router /api/v1/branch/diff [GET]
func GetDiff(ctx context.Context, c *app.RequestContext) {
	var req branch.GetDiffRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(req.GetRepoKey())
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	gitSvc := git.NewGitService()
	content, err := gitSvc.GetRawDiff(repo.Path, req.GetBase(), req.GetTarget(), req.GetFile())
	if err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	response.Success(c, map[string]string{"diff": content})
}

// GetPatch .
// @router /api/v1/branch/patch [GET]
func GetPatch(ctx context.Context, c *app.RequestContext) {
	var req branch.GetPatchRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(req.GetRepoKey())
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	gitSvc := git.NewGitService()
	patch, err := gitSvc.GetPatch(repo.Path, req.GetBase(), req.GetTarget())
	if err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	c.Header("Content-Type", "application/octet-stream")
	c.Header("Content-Disposition", fmt.Sprintf("attachment; filename=%s-%s-%s.patch", repo.Name, req.GetBase(), time.Now().Format("20060102")))
	c.Write([]byte(patch))
}
