// Code generated by hertz generator.

package stash

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _stashMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _applystashMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _clearstashMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dropstashMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _liststashMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _popstashMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _savestashMw() []app.HandlerFunc {
	// your code...
	return nil
}
