// Code generated by hertz generator.

package file

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/yi-nology/git-manage-service/biz/dal/db"
	file "github.com/yi-nology/git-manage-service/biz/model/biz/file"
	"github.com/yi-nology/git-manage-service/biz/service/git"
	"github.com/yi-nology/git-manage-service/pkg/response"
)

// GetTree .
// @router /api/v1/file/tree [GET]
func GetTree(ctx context.Context, c *app.RequestContext) {
	var req file.GetTreeRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(req.RepoKey)
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	// 默认使用HEAD
	ref := req.Ref
	if ref == "" {
		ref = "HEAD"
	}

	gitSvc := git.NewGitService()
	entries, err := gitSvc.GetTree(repo.Path, ref, req.Path, req.Recursive)
	if err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	// 转换为proto格式
	var treeEntries []*file.TreeEntry
	for _, e := range entries {
		treeEntries = append(treeEntries, &file.TreeEntry{
			Name: e.Name,
			Path: e.Path,
			Type: e.Type,
			Size: e.Size,
			Mode: e.Mode,
			Hash: e.Hash,
		})
	}

	response.Success(c, map[string]interface{}{
		"entries":      treeEntries,
		"current_ref":  ref,
		"current_path": req.Path,
	})
}

// GetBlob .
// @router /api/v1/file/blob [GET]
func GetBlob(ctx context.Context, c *app.RequestContext) {
	var req file.GetBlobRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(req.RepoKey)
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	// 默认使用HEAD
	ref := req.Ref
	if ref == "" {
		ref = "HEAD"
	}

	gitSvc := git.NewGitService()
	blob, err := gitSvc.GetBlob(repo.Path, ref, req.Path)
	if err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	response.Success(c, map[string]interface{}{
		"content":   blob.Content,
		"encoding":  blob.Encoding,
		"size":      blob.Size,
		"is_binary": blob.IsBinary,
		"mime_type": blob.MimeType,
	})
}

// GetFileHistory .
// @router /api/v1/file/history [GET]
func GetFileHistory(ctx context.Context, c *app.RequestContext) {
	var req file.GetFileHistoryRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(req.RepoKey)
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	// 默认使用HEAD
	ref := req.Ref
	if ref == "" {
		ref = "HEAD"
	}

	limit := int(req.Limit)
	if limit <= 0 {
		limit = 50
	}

	gitSvc := git.NewGitService()
	commits, err := gitSvc.GetFileHistory(repo.Path, ref, req.Path, limit)
	if err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	// 转换为proto格式
	var fileCommits []*file.FileCommit
	for _, c := range commits {
		fileCommits = append(fileCommits, &file.FileCommit{
			Hash:      c.Hash,
			ShortHash: c.ShortHash,
			Message:   c.Message,
			Author:    c.Author,
			Date:      c.Date,
		})
	}

	response.Success(c, map[string]interface{}{
		"commits": fileCommits,
	})
}
