// Code generated by hertz generator.

package system

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _systemMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getconfigMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateconfigMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listdirsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listsshkeysMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _testconnectionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _repoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getrepogitconfigMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getrepostatusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _submitchangesMw() []app.HandlerFunc {
	// your code...
	return nil
}
