// Code generated by hertz generator.

package audit

import (
	"context"
	"strconv"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/yi-nology/git-manage-service/biz/dal/db"
	"github.com/yi-nology/git-manage-service/biz/model/api"
	auditModel "github.com/yi-nology/git-manage-service/biz/model/biz/audit"
	"github.com/yi-nology/git-manage-service/pkg/response"
)

// List .
// @router /api/v1/audit/logs [GET]
func List(ctx context.Context, c *app.RequestContext) {
	var req auditModel.ListAuditLogRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	page := int(req.Page)
	if page < 1 {
		page = 1
	}
	pageSize := int(req.PageSize)
	if pageSize < 1 {
		pageSize = 20
	}

	dao := db.NewAuditLogDAO()
	logs, err := dao.FindPageWithFilters(page, pageSize, req.Action, req.Target, req.StartDate, req.EndDate)
	if err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	total, _ := dao.CountWithFilters(req.Action, req.Target, req.StartDate, req.EndDate)

	dtos := make([]api.AuditLogDTO, len(logs))
	for i, log := range logs {
		dtos[i] = api.NewAuditLogDTO(log)
	}

	c.JSON(consts.StatusOK, map[string]interface{}{
		"code": 0,
		"msg":  "success",
		"data": map[string]interface{}{
			"items": dtos,
			"total": total,
			"page":  page,
			"size":  pageSize,
		},
	})
}

// Get .
// @router /api/v1/audit/log [GET]
func Get(ctx context.Context, c *app.RequestContext) {
	idStr := c.Query("id")
	if idStr == "" {
		response.BadRequest(c, "id is required")
		return
	}

	id, err := strconv.Atoi(idStr)
	if err != nil {
		response.BadRequest(c, "invalid id")
		return
	}

	log, err := db.NewAuditLogDAO().FindByID(uint(id))
	if err != nil {
		response.NotFound(c, "audit log not found")
		return
	}

	response.Success(c, api.NewAuditLogDTO(*log))
}
