// Code generated by hertz generator.

package version

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/yi-nology/git-manage-service/biz/dal/db"
	"github.com/yi-nology/git-manage-service/biz/service/git"
	"github.com/yi-nology/git-manage-service/pkg/response"
)

// GetVersion .
// @router /api/v1/version/current [GET]
func GetVersion(ctx context.Context, c *app.RequestContext) {
	repoKey := c.Query("repo_key")
	if repoKey == "" {
		response.BadRequest(c, "repo_key is required")
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(repoKey)
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	svc := git.NewGitService()
	version, err := svc.GetDescribe(repo.Path)
	if err != nil {
		response.InternalServerError(c, "failed to determine version: "+err.Error())
		return
	}

	response.Success(c, version)
}

// ListVersions .
// @router /api/v1/version/list [GET]
func ListVersions(ctx context.Context, c *app.RequestContext) {
	repoKey := c.Query("repo_key")
	if repoKey == "" {
		response.BadRequest(c, "repo_key is required")
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(repoKey)
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	svc := git.NewGitService()
	tags, err := svc.GetTagList(repo.Path)
	if err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	response.Success(c, tags)
}

// GetNextVersions .
// @router /api/v1/version/next [GET]
func GetNextVersions(ctx context.Context, c *app.RequestContext) {
	repoKey := c.Query("repo_key")
	if repoKey == "" {
		response.BadRequest(c, "repo_key is required")
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(repoKey)
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	svc := git.NewGitService()
	info, err := svc.GetNextVersions(repo.Path)
	if err != nil {
		response.InternalServerError(c, "failed to calculate next versions: "+err.Error())
		return
	}

	response.Success(c, info)
}
