// Code generated by hertz generator.

package commit

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/yi-nology/git-manage-service/biz/dal/db"
	commit "github.com/yi-nology/git-manage-service/biz/model/biz/commit"
	"github.com/yi-nology/git-manage-service/biz/service/git"
	"github.com/yi-nology/git-manage-service/pkg/response"
)

// SearchCommits .
// @router /api/v1/commit/search [GET]
func SearchCommits(ctx context.Context, c *app.RequestContext) {
	var req commit.SearchCommitsRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(req.RepoKey)
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	gitSvc := git.NewGitService()
	commits, total, err := gitSvc.SearchCommits(repo.Path, git.SearchCommitsOptions{
		Ref:      req.Ref,
		Author:   req.Author,
		Keyword:  req.Keyword,
		Since:    req.Since,
		Until:    req.Until,
		Path:     req.Path,
		Page:     int(req.Page),
		PageSize: int(req.PageSize),
	})
	if err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	// 转换为proto格式
	var details []*commit.CommitDetail
	for _, c := range commits {
		details = append(details, &commit.CommitDetail{
			Hash:           c.Hash,
			ShortHash:      c.ShortHash,
			Message:        c.Message,
			AuthorName:     c.AuthorName,
			AuthorEmail:    c.AuthorEmail,
			AuthorDate:     c.AuthorDate,
			CommitterName:  c.CommitterName,
			CommitterEmail: c.CommitterEmail,
			CommitterDate:  c.CommitterDate,
			ParentHashes:   c.ParentHashes,
			FilesChanged:   int32(c.FilesChanged),
			Additions:      int32(c.Additions),
			Deletions:      int32(c.Deletions),
		})
	}

	response.Success(c, map[string]interface{}{
		"commits": details,
		"total":   total,
	})
}

// GetCommit .
// @router /api/v1/commit/detail [GET]
func GetCommit(ctx context.Context, c *app.RequestContext) {
	var req commit.GetCommitRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(req.RepoKey)
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	gitSvc := git.NewGitService()
	detail, changes, err := gitSvc.GetCommitDetail(repo.Path, req.Hash)
	if err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	// 转换为proto格式
	commitDetail := &commit.CommitDetail{
		Hash:           detail.Hash,
		ShortHash:      detail.ShortHash,
		Message:        detail.Message,
		AuthorName:     detail.AuthorName,
		AuthorEmail:    detail.AuthorEmail,
		AuthorDate:     detail.AuthorDate,
		CommitterName:  detail.CommitterName,
		CommitterEmail: detail.CommitterEmail,
		CommitterDate:  detail.CommitterDate,
		ParentHashes:   detail.ParentHashes,
		FilesChanged:   int32(detail.FilesChanged),
		Additions:      int32(detail.Additions),
		Deletions:      int32(detail.Deletions),
	}

	var fileChanges []*commit.FileChange
	for _, ch := range changes {
		fileChanges = append(fileChanges, &commit.FileChange{
			Path:      ch.Path,
			Status:    ch.Status,
			Additions: int32(ch.Additions),
			Deletions: int32(ch.Deletions),
			OldPath:   ch.OldPath,
		})
	}

	response.Success(c, map[string]interface{}{
		"commit": commitDetail,
		"files":  fileChanges,
	})
}

// GetCommitDiff .
// @router /api/v1/commit/diff [GET]
func GetCommitDiff(ctx context.Context, c *app.RequestContext) {
	var req commit.GetCommitDiffRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(req.RepoKey)
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	gitSvc := git.NewGitService()
	diff, err := gitSvc.GetCommitDiff(repo.Path, req.Hash, req.File)
	if err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	response.Success(c, map[string]interface{}{
		"diff": diff,
	})
}
