// Code generated by hertz generator.

package stats

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _statsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getstatsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listbranchesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listauthorsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listcommitsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _exportMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _exportcsvMw() []app.HandlerFunc {
	// your code...
	return nil
}

// 代码行统计相关 middleware
func _linesMw() []app.HandlerFunc {
	return nil
}

func _getlinestatsMw() []app.HandlerFunc {
	return nil
}

func _getlinestatsconfMw() []app.HandlerFunc {
	return nil
}

func _savelinestatsconfMw() []app.HandlerFunc {
	return nil
}

func _linesExportMw() []app.HandlerFunc {
	return nil
}

func _exportlinestatscsvMw() []app.HandlerFunc {
	return nil
}
