// Code generated by hertz generator. DO NOT EDIT.

package stats

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	stats "github.com/yi-nology/git-manage-service/biz/handler/stats"
)

/*
 This file will register all the routes of the services in the master idl.
 And it will update automatically when you use the "update" command for the idl.
 So don't modify the contents of the file, or your code will be deleted when it is updated.
*/

// Register register routes based on the IDL 'api.${HTTP Method}' annotation.
func Register(r *server.Hertz) {

	root := r.Group("/", rootMw()...)
	{
		_api := root.Group("/api", _apiMw()...)
		{
			_v1 := _api.Group("/v1", _v1Mw()...)
			{
				_stats := _v1.Group("/stats", _statsMw()...)
				_stats.GET("/analyze", append(_getstatsMw(), stats.GetStats)...)
				_stats.GET("/authors", append(_listauthorsMw(), stats.ListAuthors)...)
				_stats.GET("/branches", append(_listbranchesMw(), stats.ListBranches)...)
				_stats.GET("/commits", append(_listcommitsMw(), stats.ListCommits)...)
				{
					_export := _stats.Group("/export", _exportMw()...)
					_export.GET("/csv", append(_exportcsvMw(), stats.ExportCSV)...)
				}
				// 代码行统计相关路由
				{
					_lines := _stats.Group("/lines", _linesMw()...)
					_lines.GET("", append(_getlinestatsMw(), stats.GetLineStats)...)
					_lines.GET("/config", append(_getlinestatsconfMw(), stats.GetLineStatsConfig)...)
					_lines.POST("/config", append(_savelinestatsconfMw(), stats.SaveLineStatsConfig)...)
					{
						_linesExport := _lines.Group("/export", _linesExportMw()...)
						_linesExport.GET("/csv", append(_exportlinestatscsvMw(), stats.ExportLineStatsCSV)...)
					}
				}
			}
		}
	}
}
