// Code generated by hertz generator.

package commit

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commitMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcommitMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcommitdiffMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchcommitsMw() []app.HandlerFunc {
	// your code...
	return nil
}
