// Code generated by hertz generator.

package system

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"
	"strings"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/yi-nology/git-manage-service/biz/dal/db"
	"github.com/yi-nology/git-manage-service/biz/model/api"
	common "github.com/yi-nology/git-manage-service/biz/model/common"
	systemModel "github.com/yi-nology/git-manage-service/biz/model/system"
	"github.com/yi-nology/git-manage-service/biz/service/audit"
	"github.com/yi-nology/git-manage-service/biz/service/auth"
	"github.com/yi-nology/git-manage-service/biz/service/git"
	"github.com/yi-nology/git-manage-service/pkg/appinfo"
	"github.com/yi-nology/git-manage-service/pkg/configs"
	"github.com/yi-nology/git-manage-service/pkg/response"
)

// GetConfig .
// @router /api/v1/system/config [GET]
func GetConfig(ctx context.Context, c *app.RequestContext) {
	gitSvc := git.NewGitService()
	name, email, _ := gitSvc.GetGlobalGitUser()

	response.Success(c, map[string]interface{}{
		"debug_mode":   configs.DebugMode,
		"author_name":  name,
		"author_email": email,
	})
}

// UpdateConfig .
// @router /api/v1/system/config [POST]
func UpdateConfig(ctx context.Context, c *app.RequestContext) {
	var req systemModel.UpdateConfigRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	configs.DebugMode = req.DebugMode

	gitSvc := git.NewGitService()
	if err := gitSvc.SetGlobalGitUser(req.AuthorName, req.AuthorEmail); err != nil {
		response.InternalServerError(c, "Failed to set git config: "+err.Error())
		return
	}

	response.Success(c, map[string]interface{}{
		"debug_mode":   configs.DebugMode,
		"author_name":  req.AuthorName,
		"author_email": req.AuthorEmail,
	})
}

// ListDirs .
// @router /api/v1/system/dirs [GET]
func ListDirs(ctx context.Context, c *app.RequestContext) {
	var req systemModel.ListDirsRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	currentPath := req.Path
	if currentPath == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			currentPath = "/"
		} else {
			currentPath = home
		}
	}

	entries, err := os.ReadDir(currentPath)
	if err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	var dirs []api.DirItem
	for _, entry := range entries {
		if entry.IsDir() && !strings.HasPrefix(entry.Name(), ".") {
			if req.Search != "" && !strings.Contains(strings.ToLower(entry.Name()), strings.ToLower(req.Search)) {
				continue
			}
			dirs = append(dirs, api.DirItem{
				Name: entry.Name(),
				Path: filepath.Join(currentPath, entry.Name()),
			})
		}
	}

	sort.Slice(dirs, func(i, j int) bool {
		return dirs[i].Name < dirs[j].Name
	})

	parent := filepath.Dir(currentPath)
	if currentPath == "/" {
		parent = ""
	}

	response.Success(c, api.ListDirsResp{
		Parent:  parent,
		Current: currentPath,
		Dirs:    dirs,
	})
}

// ListSSHKeys .
// @router /api/v1/system/ssh-keys [GET]
func ListSSHKeys(ctx context.Context, c *app.RequestContext) {
	home, err := os.UserHomeDir()
	if err != nil {
		response.InternalServerError(c, "cannot find home dir")
		return
	}

	sshDir := filepath.Join(home, ".ssh")
	entries, err := os.ReadDir(sshDir)
	if err != nil {
		response.Success(c, []api.SSHKey{})
		return
	}

	var keys []api.SSHKey
	for _, entry := range entries {
		if !entry.IsDir() {
			keys = append(keys, api.SSHKey{
				Name: entry.Name(),
				Path: filepath.Join(sshDir, entry.Name()),
			})
		}
	}

	response.Success(c, keys)
}

// TestConnection .
// @router /api/v1/system/test-connection [POST]
func TestConnection(ctx context.Context, c *app.RequestContext) {
	var req systemModel.TestConnectionRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	gitSvc := git.NewGitService()
	authSvc := auth.NewAuthService()

	var err error

	// 根据认证类型选择测试方法
	switch req.AuthType {
	case "ssh_db", "ssh_database":
		// 数据库 SSH 密钥 - 需要从 auth_key 获取密钥内容
		// auth_key 格式: credential:<id> 或直接是私钥内容
		if strings.HasPrefix(req.AuthKey, "credential:") {
			credIDStr := strings.TrimPrefix(req.AuthKey, "credential:")
			credID := parseUint(credIDStr)
			if credID > 0 {
				privateKey, passphrase, keyErr := authSvc.GetCredentialKeyContent(credID)
				if keyErr != nil {
					response.Success(c, map[string]string{"status": "failed", "error": "failed to load credential: " + keyErr.Error()})
					return
				}
				err = gitSvc.TestRemoteConnectionWithDBKey(req.Url, privateKey, passphrase)
			} else {
				err = fmt.Errorf("invalid credential ID")
			}
		} else {
			// 直接使用私钥内容
			err = gitSvc.TestRemoteConnectionWithDBKey(req.Url, req.AuthKey, req.AuthSecret)
		}
	case "ssh_local":
		// 本地 SSH 密钥文件
		err = gitSvc.TestRemoteConnectionWithLocalKey(req.Url, req.AuthKey, req.AuthSecret)
	case "http", "https":
		// HTTP/HTTPS 认证
		err = gitSvc.TestRemoteConnectionWithHTTP(req.Url, req.AuthKey, req.AuthSecret)
	default:
		// 无认证或自动检测
		err = gitSvc.TestRemoteConnection(req.Url)
	}

	if err != nil {
		response.Success(c, map[string]string{"status": "failed", "error": err.Error()})
		return
	}

	response.Success(c, map[string]string{"status": "success"})
}

// parseUint 解析 uint
func parseUint(s string) uint {
	var result uint
	fmt.Sscanf(s, "%d", &result)
	return result
}

// GetRepoStatus .
// @router /api/v1/system/repo/status [GET]
func GetRepoStatus(ctx context.Context, c *app.RequestContext) {
	repoKey := c.Query("repo_key")
	if repoKey == "" {
		response.BadRequest(c, "repo_key is required")
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(repoKey)
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	gitSvc := git.NewGitService()
	status, err := gitSvc.GetStatus(repo.Path)
	if err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	response.Success(c, map[string]string{"status": status})
}

// GetRepoGitConfig .
// @router /api/v1/system/repo/git-config [GET]
func GetRepoGitConfig(ctx context.Context, c *app.RequestContext) {
	repoKey := c.Query("repo_key")
	if repoKey == "" {
		response.BadRequest(c, "repo_key is required")
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(repoKey)
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	gitSvc := git.NewGitService()
	name, email, _ := gitSvc.GetGitUser(repo.Path)

	response.Success(c, map[string]string{
		"name":  name,
		"email": email,
	})
}

// SubmitChanges .
// @router /api/v1/system/repo/submit [POST]
func SubmitChanges(ctx context.Context, c *app.RequestContext) {
	var req systemModel.SubmitChangesRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	if req.Message == "" {
		response.BadRequest(c, "commit message is required")
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(req.RepoKey)
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	gitSvc := git.NewGitService()

	// Selective file staging or add all
	if len(req.Files) > 0 {
		if err := gitSvc.AddFiles(repo.Path, req.Files); err != nil {
			response.InternalServerError(c, "Failed to stage files: "+err.Error())
			return
		}
	} else {
		if err := gitSvc.AddAll(repo.Path); err != nil {
			response.InternalServerError(c, "Failed to stage files: "+err.Error())
			return
		}
	}

	status, _ := gitSvc.GetStatus(repo.Path)
	fullMsg := fmt.Sprintf("%s\n\nGit Status Snapshot:\n%s", req.Message, status)

	if err := gitSvc.Commit(repo.Path, fullMsg, req.AuthorName, req.AuthorEmail); err != nil {
		_ = gitSvc.Reset(repo.Path)
		response.InternalServerError(c, "Failed to commit: "+err.Error())
		return
	}

	msg := "Committed successfully"

	if req.Push {
		if err := gitSvc.PushCurrent(repo.Path); err != nil {
			msg += ", but push failed: " + err.Error()
			response.Success(c, map[string]string{"message": msg, "warning": "push_failed"})
			return
		}
		msg += " and pushed to remote"
	}

	audit.AuditSvc.Log(c, "SUBMIT_CHANGES", "repo:"+repo.Key, map[string]interface{}{
		"message": req.Message,
		"push":    req.Push,
		"files":   req.Files,
	})

	response.Success(c, map[string]string{"message": msg})
}

// GetAppInfo 获取应用版本信息
// @router /api/v1/system/app-info [GET]
func GetAppInfo(ctx context.Context, c *app.RequestContext) {
	response.Success(c, map[string]string{
		"app_name":   appinfo.AppName,
		"version":    appinfo.Version,
		"build_time": appinfo.BuildTime,
		"git_commit": appinfo.GitCommit,
	})
}

// SelectDirectory 打开系统目录选择对话框
// @router /api/v1/system/select-directory [POST]
func SelectDirectory(ctx context.Context, c *app.RequestContext) {
	var req struct {
		Title string `json:"title"`
	}
	_ = c.Bind(&req)

	title := req.Title
	if title == "" {
		title = "选择目录"
	}

	// 尝试根据操作系统打开目录选择对话框
	var result string
	var err error

	switch runtime.GOOS {
	case "darwin":
		// macOS: 使用 osascript
		cmd := fmt.Sprintf(`tell application "System Events" to activate
return POSIX path of (choose folder with prompt "%s")`, title)
		result, err = execCommand("osascript", "-e", cmd)
	case "windows":
		// Windows: 使用 powershell
		cmd := fmt.Sprintf(`Add-Type -AssemblyName System.Windows.Forms; $f = New-Object System.Windows.Forms.FolderBrowserDialog; $f.Description = '%s'; $f.ShowDialog() | Out-Null; if ($f.SelectedPath) { Write-Output $f.SelectedPath }`, title)
		result, err = execCommand("powershell", "-Command", cmd)
	default:
		// Linux 或其他系统: 返回错误，建议使用目录浏览功能
		errorMsg := "Directory dialog not supported on this platform. Please use the directory browser instead."
		response.InternalServerError(c, errorMsg)
		return
	}

	if err != nil {
		// 提供备选方案：使用目录浏览功能
		errorMsg := "Failed to open directory dialog: " + err.Error() + ". Please use the directory browser instead."
		response.InternalServerError(c, errorMsg)
		return
	}

	path := strings.TrimSpace(result)
	if path == "" {
		response.Success(c, map[string]string{"path": "", "cancelled": "true"})
		return
	}

	response.Success(c, map[string]string{"path": path, "cancelled": "false"})
}

// execCommand 执行系统命令
func execCommand(name string, args ...string) (string, error) {
	cmd := exec.Command(name, args...)
	output, err := cmd.Output()
	if err != nil {
		return "", err
	}
	return string(output), nil
}
