// @ts-check
// Cynhyrchion y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBackendURL() {
  return window['go']['main']['App']['GetBackendURL']
}

export function GetBuildTime() {
  return window['go']['main']['App']['GetBuildTime']
}

export function GetGitCommit() {
  return window['go']['main']['App']['GetGitCommit']
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']
}
