// Code generated by Kitex v0.15.2. DO NOT EDIT.

package gitservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	git "github.com/yi-nology/git-manage-service/biz/kitex_gen/git"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	ListRepos(ctx context.Context, Req *git.ListReposRequest, callOptions ...callopt.Option) (r *git.ListReposResponse, err error)
	GetRepo(ctx context.Context, Req *git.GetRepoRequest, callOptions ...callopt.Option) (r *git.GetRepoResponse, err error)
	ListBranches(ctx context.Context, Req *git.ListBranchesRequest, callOptions ...callopt.Option) (r *git.ListBranchesResponse, err error)
	CreateBranch(ctx context.Context, Req *git.CreateBranchRequest, callOptions ...callopt.Option) (r *git.CreateBranchResponse, err error)
	DeleteBranch(ctx context.Context, Req *git.DeleteBranchRequest, callOptions ...callopt.Option) (r *git.DeleteBranchResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kGitServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kGitServiceClient struct {
	*kClient
}

func (p *kGitServiceClient) ListRepos(ctx context.Context, Req *git.ListReposRequest, callOptions ...callopt.Option) (r *git.ListReposResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListRepos(ctx, Req)
}

func (p *kGitServiceClient) GetRepo(ctx context.Context, Req *git.GetRepoRequest, callOptions ...callopt.Option) (r *git.GetRepoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetRepo(ctx, Req)
}

func (p *kGitServiceClient) ListBranches(ctx context.Context, Req *git.ListBranchesRequest, callOptions ...callopt.Option) (r *git.ListBranchesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListBranches(ctx, Req)
}

func (p *kGitServiceClient) CreateBranch(ctx context.Context, Req *git.CreateBranchRequest, callOptions ...callopt.Option) (r *git.CreateBranchResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateBranch(ctx, Req)
}

func (p *kGitServiceClient) DeleteBranch(ctx context.Context, Req *git.DeleteBranchRequest, callOptions ...callopt.Option) (r *git.DeleteBranchResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteBranch(ctx, Req)
}
