// Code generated by Kitex v0.15.2. DO NOT EDIT.
package gitservice

import (
	server "github.com/cloudwego/kitex/server"
	git "github.com/yi-nology/git-manage-service/biz/kitex_gen/git"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler git.GitService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler git.GitService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
