// Code generated by hertz generator.

package branch

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _branchMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _checkoutMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _compareMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdiffMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mergeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _merge0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mergecheckMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpatchMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _pullMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _pushMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateMw() []app.HandlerFunc {
	// your code...
	return nil
}
